### ISSUE TITLE
Alterar chamadas do themePath para a função Asset()

### ISSUE THREAD

**Issue by richardsantos** [tray-tecnologia/theme-template#26]
Deverá ser alterado em todos os pontos, as chamadas:
`themePath` para `asset()`

**Comment by lkusunoki** [comment]
todos os temas que já estão feitos deverão sofrer alteração?

**Comment by richardsantos** [comment]
@lkusunoki a themePath não vai parar de funcionar, mas estamos deprecando.
A `asset()` tem muitos benefícios que a themePath não tem. Por isso vai ser a nossa recomendação de agora em diante.

Sugiro que daqui pra frente usem a `asset()`, mas podem ficar tranquilos com os layouts que já utilizam a `themePath`.

**Comment by lkusunoki** [comment]
Legal, já existe alguma melhoria para o asset() pegar as configurações da administração?
Hoje ele só aceita as configurações do settings.

**Comment by richardsantos** [comment]
@lkusunoki a princípio pensamos em disponibilizar apenas o objeto `settings`.
Mas, talvez possamos rever isso...
